#!/bin/bash

set -e

pkgos-dh_auto_test --no-py2 'pbr\.tests(?!.*test_packaging\.TestRequirementParsing\.test_requirement_parsing.*|.*test_wsgi\.TestWsgiScripts\.test_wsgi_script_install.*|.*test_packaging\.TestPEP517Support\.test_pep_517_support.*)'
